config/routes.rb
Rails.application.routes.draw do
  resources :contracts do
    member do
      get 'thoa_thuan'
      get 'tra_tien'
      get 'ket_thuc'
      get 'huy_keo'
      get 'tra_lai_tien'
      get 'tao_moi'
      patch 'thoa_thuan', to: 'contracts#thoa_thuan'
      patch 'huy_keo', to: 'contracts#huy_keo'
      patch 'tra_tien', to: 'contracts#tra_tien'
      patch 'tra_lai_tien', to: 'contracts#tra_lai_tien'
      patch 'ket_thuc', to: 'contracts#ket_thuc'
      patch 'tao_moi', to: 'contracts#tao_moi'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
  include AASM

  aasm :column => 'state' do
    state :new, initial: true
    state :dealt
    state :paid
    state :ended

    after_all_transitions :log_status_change
    event :deal do
      transitions from: :new, to: :dealt
    end

    event :undeal do
      transitions from: :dealt, to: :new
    end

    event :pay do
      transitions from: :dealt, to: :paid
    end

    event :return_money do
      transitions from: :paid, to: :dealt
    end
    
    event :end do
      transitions from: :paid, to: :ended
    end

    event :renew do
      transitions from: :ended, to: :new
    end
  end

  def log_status_change
    puts "============================SAU KHI TẤT CẢ CÁC TRANSTION ĐƯỢC THỰC HIỆN==============================="
    puts "Thay đổi từ --> #{aasm.from_state} <-- tới --> #{aasm.to_state} <-- (state: --> #{aasm.current_event} <--)"
    puts "======================================================================================================"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy, :thoa_thuan, :huy_keo, :tra_tien, :ket_thuc, :tra_lai_tien, :tao_moi]

  # GET /contracts
  # GET /contracts.json
  def index
    @contracts = Contract.all
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    @contract = Contract.new(contract_params)

    respond_to do |format|
      if @contract.save
        format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
        format.json { render :show, status: :created, location: @contract }
      else
        format.html { render :new }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update
    respond_to do |format|
      if @contract.update(contract_params)
       
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  def thoa_thuan
    respond_to do |format|
      if @contract.deal!
        format.html { redirect_to contracts_path, notice: "Hợp đồng số ##{@contract.id} đã thỏa thuận" }
      end
    end
  end

  def huy_keo
    respond_to do |format|
      if @contract.undeal!
        format.html { redirect_to contracts_path, notice: "Hợp đồng số ##{@contract.id} đã bị hủy kèo" }
      end
    end
  end

  def tra_tien
    respond_to do |format|
      if @contract.pay!
        format.html { redirect_to contracts_path, notice: "Hợp đồng số ##{@contract.id} đã thanh toán" }
      end
    end
  end

  def tra_lai_tien
    respond_to do |format|
      if @contract.return_money!
        format.html { redirect_to contracts_path, notice: "Hợp đồng số ##{@contract.id} đã bị đòi lại tiền" }
      end
    end
  end

  def ket_thuc
    respond_to do |format|
      if @contract.end!
       format.html { redirect_to contracts_path, notice: "Hợp đồng số ##{@contract.id} đã kết thúc" }
      end
    end
  end

  def tao_moi
    respond_to do |format|
      if @contract.renew!
        format.html { redirect_to contracts_path, notice: "Hợp đồng số ##{@contract.id} đã được tạo mới" }
      end
    end
  end

  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_contract
      @contract = Contract.find(params[:id])
    end

    def contract_params
      params.require(:contract).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_with(model: contract, local: true) do |form| %>
  <% if contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
        <% contract.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
  <div class='container-fluid'>
    <div class="text-center">
      <p id="notice"><%= notice %></p>
    </div>
    <div class="row">
      <h1>Contracts</h1>
    </div>
    <div class="row">
      <div class="col-sm">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Hợp đồng</th>
              <th scope="col">Trạng thái</th>
            </tr>
          </thead>
          <tbody>
            <% @contracts.each do |contract| %>
            <% if contract.may_deal? %>
            <tr>
              <td><%= contract.name %></td>
              <td><%= contract.state %></td>
              <td><%= link_to 'Thỏa thuận', thoa_thuan_contract_path(contract) %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-sm">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Hợp đồng</th>
              <th scope="col">Trạng thái</th>
            </tr>
          </thead>
          <tbody>
            <% @contracts.each do |contract| %>
            <% if contract.may_pay? %>
            <tr>
              <td><%= contract.name %></td>
              <td><%= contract.state %></td>
              <td><%= link_to 'Lấy tiền', tra_tien_contract_path(contract) %></td>
              <td><%= link_to 'Hủy kèo', huy_keo_contract_path(contract) %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-sm">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Hợp đồng</th>
              <th scope="col">Trạng thái</th>
            </tr>
          </thead>
          <tbody>
            <% @contracts.each do |contract| %>
            <% if contract.may_end? %>
            <tr>
              <td><%= contract.name %></td>
              <td><%= contract.state %></td>
              <td><%= link_to 'Kết thúc', ket_thuc_contract_path(contract) %></td>
              <td><%= link_to 'Trả lại tiền', tra_lai_tien_contract_path(contract) %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-sm">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Hợp đồng</th>
              <th scope="col">Trạng thái</th>
            </tr>
          </thead>
          <tbody>
            <% @contracts.each do |contract| %>
            <% if contract.ended? %>
            <tr>
              <td><%= contract.name %></td>
              <td><%= contract.state %></td>
              <td><%= link_to 'Renew hợp đồng', tao_moi_contract_path(contract) %></td>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/contracts/new.html.erb
<h1>New Contract</h1>

<%= render 'form', contract: @contract %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contract.name %>
</p>

<p>
  <strong>State:</strong>
  <%= @contract.state %>
</p>

<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoAasm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>